using System.Globalization;
using System.Numerics;
using System.Text;

namespace BallisticEngine.Tools.GeneratePrimitives;

// Writes the engine's default primitive meshes (Cube, Sphere, Plane) as Wavefront .obj source
// assets into <project>/Assets/Default/Meshes/. The editor's "Create > 3D Object" then references
// these shared, GUID-backed assets (so the mesh serializes into the scene and survives reload)
// instead of building a fresh, unsaveable runtime mesh each time.
//
// The geometry here MUST stay in sync with the fallback builders in
// BallisticEngine.Editor/EditorApp/Primitives.cs:
//   Cube   = 1 m cube, half-extent 0.5, one normal/UV per face (24 verts)
//   Sphere = 1 m radius, 32 longitudes x 24 latitudes
//   Plane  = 5x5 m on the XZ ground plane, facing +Y
//
// .obj is already a first-class mesh format in the asset pipeline (ModelImporter -> .bmesh), so no
// new importer/loader is needed. The companion .meta files are written with generateMaterials=false
// and splitByNodes=false so the import is geometry-only (no sibling "_Materials" folder, no node
// split) and flipUVs=false because the UVs below are authored in the engine's convention already.
internal static class Program {
    static int Main(string[] args) {
        var repoRoot = FindRepoRoot();
        var projectPath = args.Length > 0
            ? Path.GetFullPath(args[0])
            : Path.Combine(repoRoot, "SampleProject");

        var meshesDir = Path.Combine(projectPath, "Assets", "Default", "Meshes");
        Directory.CreateDirectory(meshesDir);

        // Fixed GUIDs so the generated assets keep a stable identity across regenerations — scenes
        // reference primitives by these, so they MUST NOT change once shipped. The .meta is only
        // written if absent (same rule as the pipeline's EnsureMeta), so a hand-edited meta wins.
        Write(meshesDir, "Cube", "1373de82334d41269f8bb0028d678db9", Cube());
        Write(meshesDir, "Sphere", "f6372b95f56f4f029d948791a97ddd22", Sphere(1f, 32, 24));
        Write(meshesDir, "Plane", "b0e2ad6d7de340dfad07e7eb539e3f80", Plane());

        Console.WriteLine($"Done. Wrote Cube/Sphere/Plane (.obj + .meta) to {meshesDir}");
        Console.WriteLine("Re-run the editor (or Assets > Refresh) so the pipeline imports them.");
        return 0;
    }

    // ---- Output ------------------------------------------------------------

    static void Write(string dir, string name, string guidHex, Mesh mesh) {
        var objPath = Path.Combine(dir, name + ".obj");
        File.WriteAllText(objPath, ToObj(name, mesh));
        Console.WriteLine($"  {name}.obj  ({mesh.Vertices.Count} verts, {mesh.Indices.Count / 3} tris)");

        // ModelImporter geometry-only import: no generated material folder, no node split, and no
        // UV flip (our UVs are already authored in the engine's convention). Matches the engine's
        // ModelImporter settings shape; written only when no meta exists so the GUID stays stable.
        var metaPath = objPath + ".meta";
        if (File.Exists(metaPath)) {
            Console.WriteLine($"    (keeping existing {name}.obj.meta)");
            return;
        }
        var guid = Guid.Parse(guidHex);
        File.WriteAllText(metaPath, $$"""
            {
              "version": 1,
              "guid": "{{guid}}",
              "importer": "ModelImporter",
              "settings": {
                "flipUVs": false,
                "meshIndex": -1,
                "generateMaterials": false,
                "splitByNodes": false
              }
            }
            """ + "\n");
    }

    // Wavefront OBJ with positions, UVs, and per-vertex normals. Because each of our vertices
    // already carries its own normal+UV (faces don't share verts where the normal differs), every
    // face index points at the same v/vt/vn triple — a clean 1:1 mapping.
    static string ToObj(string name, Mesh mesh) {
        var sb = new StringBuilder();
        sb.Append("# Ballistic Engine default primitive: ").Append(name).Append('\n');
        sb.Append("# Generated by Tools/GeneratePrimitives — do not edit by hand.\n");
        sb.Append("o ").Append(name).Append('\n');

        var ci = CultureInfo.InvariantCulture;
        foreach (Vector3 v in mesh.Vertices)
            sb.Append("v ").Append(v.X.ToString("R", ci)).Append(' ')
              .Append(v.Y.ToString("R", ci)).Append(' ').Append(v.Z.ToString("R", ci)).Append('\n');
        foreach (Vector2 t in mesh.UVs)
            sb.Append("vt ").Append(t.X.ToString("R", ci)).Append(' ').Append(t.Y.ToString("R", ci)).Append('\n');
        foreach (Vector3 n in mesh.Normals)
            sb.Append("vn ").Append(n.X.ToString("R", ci)).Append(' ')
              .Append(n.Y.ToString("R", ci)).Append(' ').Append(n.Z.ToString("R", ci)).Append('\n');

        for (var i = 0; i < mesh.Indices.Count; i += 3) {
            // OBJ is 1-indexed; v/vt/vn share the same index for our unwelded verts.
            var a = mesh.Indices[i] + 1;
            var b = mesh.Indices[i + 1] + 1;
            var c = mesh.Indices[i + 2] + 1;
            sb.Append("f ")
              .Append(a).Append('/').Append(a).Append('/').Append(a).Append(' ')
              .Append(b).Append('/').Append(b).Append('/').Append(b).Append(' ')
              .Append(c).Append('/').Append(c).Append('/').Append(c).Append('\n');
        }

        return sb.ToString();
    }

    // ---- Geometry (mirrors BallisticEngine.Editor/EditorApp/Primitives.cs) ---

    sealed class Mesh {
        public readonly List<Vector3> Vertices = new();
        public readonly List<Vector3> Normals = new();
        public readonly List<Vector2> UVs = new();
        public readonly List<uint> Indices = new();
    }

    static Mesh Cube() {
        var m = new Mesh();

        void Face(Vector3 origin, Vector3 right, Vector3 up) {
            Vector3 normal = Vector3.Normalize(Vector3.Cross(right, up));
            var b = (uint)m.Vertices.Count;
            m.Vertices.Add(origin);
            m.Vertices.Add(origin + right);
            m.Vertices.Add(origin + right + up);
            m.Vertices.Add(origin + up);
            for (var i = 0; i < 4; i++) m.Normals.Add(normal);
            m.UVs.Add(new Vector2(0, 0)); m.UVs.Add(new Vector2(1, 0));
            m.UVs.Add(new Vector2(1, 1)); m.UVs.Add(new Vector2(0, 1));
            m.Indices.AddRange(new[] { b, b + 1, b + 2, b, b + 2, b + 3 });
        }

        const float h = 0.5f;
        Face(new Vector3(-h, -h, h), new Vector3(1, 0, 0), new Vector3(0, 1, 0));   // +Z front
        Face(new Vector3(h, -h, -h), new Vector3(-1, 0, 0), new Vector3(0, 1, 0));  // -Z back
        Face(new Vector3(h, -h, h), new Vector3(0, 0, -1), new Vector3(0, 1, 0));   // +X right
        Face(new Vector3(-h, -h, -h), new Vector3(0, 0, 1), new Vector3(0, 1, 0));  // -X left
        Face(new Vector3(-h, h, h), new Vector3(1, 0, 0), new Vector3(0, 0, -1));   // +Y top
        Face(new Vector3(-h, -h, -h), new Vector3(1, 0, 0), new Vector3(0, 0, 1));  // -Y bottom
        return m;
    }

    static Mesh Plane() {
        const float h = 2.5f;   // 5x5 m plane
        var m = new Mesh();
        m.Vertices.AddRange(new[] {
            new Vector3(-h, 0, h), new Vector3(h, 0, h), new Vector3(h, 0, -h), new Vector3(-h, 0, -h),
        });
        for (var i = 0; i < 4; i++) m.Normals.Add(Vector3.UnitY);
        m.UVs.AddRange(new[] { new Vector2(0, 0), new Vector2(1, 0), new Vector2(1, 1), new Vector2(0, 1) });
        m.Indices.AddRange(new uint[] { 0, 1, 2, 0, 2, 3 });
        return m;
    }

    static Mesh Sphere(float radius, int longitudes, int latitudes) {
        var m = new Mesh();
        for (var lat = 0; lat <= latitudes; lat++) {
            float theta = lat * MathF.PI / latitudes;       // 0..pi
            float sinT = MathF.Sin(theta), cosT = MathF.Cos(theta);
            for (var lon = 0; lon <= longitudes; lon++) {
                float phi = lon * MathF.Tau / longitudes;   // 0..2pi
                var n = new Vector3(MathF.Cos(phi) * sinT, cosT, MathF.Sin(phi) * sinT);
                m.Vertices.Add(n * radius);
                m.Normals.Add(n);
                m.UVs.Add(new Vector2(lon / (float)longitudes, lat / (float)latitudes));
            }
        }

        var stride = longitudes + 1;
        for (var lat = 0; lat < latitudes; lat++) {
            for (var lon = 0; lon < longitudes; lon++) {
                var a = (uint)(lat * stride + lon);
                var b = (uint)(a + stride);
                m.Indices.AddRange(new[] { a, b, a + 1, a + 1, b, b + 1 });
            }
        }
        return m;
    }

    // ---- Repo discovery ----------------------------------------------------

    static string FindRepoRoot() {
        var dir = AppContext.BaseDirectory;
        while (dir is not null) {
            if (File.Exists(Path.Combine(dir, "BallisticEngine.slnx")))
                return dir;
            dir = Path.GetDirectoryName(dir.TrimEnd(Path.DirectorySeparatorChar));
        }
        // Fall back to two levels up from the tool source (Tools/GeneratePrimitives -> repo).
        return Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
    }
}
