using System.Text;
using BallisticEngine.AssetPipeline;
using BallisticEngine.Serialization;

namespace BallisticEngine.Cli.Commands;

// `bal agents <project>` — generates the project's AGENTS.md: the toolchain manual an AI agent
// reads first. Project facts (scenes, game components, asset inventory) come from live reflection
// and the .meta sidecars, so the doc can never go stale — regenerate after adding scripts/scenes.
internal sealed class AgentsCommand : ICommand {
    public string Name => "agents";
    public string Summary => "Generate the project's AGENTS.md (toolchain + project map).";
    public string Usage => "Usage: bal agents <project-dir-or-any-path-inside> [--out <path>]";

    public int Run(string[] args) {
        string? pathArg = null, outPath = null;
        for (int i = 0; i < args.Length; i++) {
            switch (args[i]) {
                case "--out": outPath = ++i < args.Length ? args[i] : throw new CliUsageException("--out needs a value"); break;
                default:
                    if (pathArg is null) pathArg = args[i];
                    else throw new CliUsageException($"unexpected argument '{args[i]}'");
                    break;
            }
        }
        if (pathArg is null) throw new CliUsageException("expected a project path");
        string root = SceneFile.ResolveProjectRoot(pathArg);
        BallisticProject project = BallisticProject.Open(root);
        SceneFile.BuildRegistryForRoot(root);
        outPath ??= Path.Combine(root, "AGENTS.md");

        var sb = new StringBuilder(16 * 1024);
        sb.AppendLine($"# {project.Manifest?.Name ?? "Ballistic project"} — agent guide");
        sb.AppendLine();
        sb.AppendLine("Generated by `bal agents` — REGENERATE after adding scripts or scenes, do not hand-edit.");
        sb.AppendLine("This is a **Ballistic Engine** project (custom C#/.NET 9 engine, Unity-like idioms; NOT Unity).");
        sb.AppendLine();

        // ---- toolchain ----------------------------------------------------------
        sb.AppendLine("## Toolchain (everything works headless)");
        sb.AppendLine();
        sb.AppendLine("`bal` CLI (engine repo: `dotnet build BallisticEngine.slnx`, exe at `BallisticEngine.Cli/bin/Debug/net9.0/bal.exe`):");
        sb.AppendLine();
        sb.AppendLine("| Verb | What it does |");
        sb.AppendLine("|---|---|");
        sb.AppendLine("| `bal map <project>` | Project overview: scenes, script components, asset inventory. Run this FIRST. |");
        sb.AppendLine("| `bal schema [--type X]` | Component catalog: every component + member types/ranges. Ground truth, never guess members. |");
        sb.AppendLine("| `bal describe <scene>` | Scene summary (entity tree + components). |");
        sb.AppendLine("| `bal scene get/set/add-entity/add-component/remove-*/find` | Block-level scene editing with typed validation. Never hand-edit scene YAML. |");
        sb.AppendLine("| `bal validate <scene>` | Static check: types, members, refs — run after any scene change. |");
        sb.AppendLine("| `bal import <project>` | Idempotent asset import (run after adding files externally). |");
        sb.AppendLine("| `bal assets resolve/refs/list` | Path<->guid, reverse references (\"what breaks if I touch this\"). |");
        sb.AppendLine("| `bal simulate <scene> --steps N --watch Entity [--input script.json]` | Headless play with numeric probes + scripted input. Assert behavior from DATA. |");
        sb.AppendLine("| `bal render <scene> [--orbit N] [--idmap]` | Deterministic screenshots; multi-view orbit; entity-ID maps. |");
        sb.AppendLine("| `bal imgdiff <a> <b> [--out heatmap]` | Perceptual diff with mean + hotspot budgets. |");
        sb.AppendLine("| `bal agents <project>` | Regenerate this file. |");
        sb.AppendLine();
        sb.AppendLine("Player env-var harness (`dotnet run --project BallisticEngine.Runtime <project>`):");
        sb.AppendLine();
        sb.AppendLine("| Env | Effect |");
        sb.AppendLine("|---|---|");
        sb.AppendLine("| `BALLISTIC_SCENE=<Assets/...scene>` | Load this scene instead of the startup scene. |");
        sb.AppendLine("| `BALLISTIC_SCREENSHOT=<path.bmp>` | Save a frame + `.stats.json` sidecar, then exit (`_EXIT=0` to keep running, `_FRAME=N` default 180). |");
        sb.AppendLine("| `BALLISTIC_SCREENSHOT_PAUSED=1` | No play mode: bit-exact deterministic frames. |");
        sb.AppendLine("| `BALLISTIC_DETERMINISTIC=1` | Kill all frame-to-frame variance (TAA/SSGI/volumetric/auto-exposure) — frame 60 == frame 240. |");
        sb.AppendLine("| `BALLISTIC_IDMAP=<path>` | Entity-ID map: `<path>.json` per-entity screen bboxes + `<path>.bmp` segmentation. |");
        sb.AppendLine("| `BALLISTIC_FX_SSGI/SSR/SSAO/VOLUMETRIC/DOF/...=0\\|1` | Force individual effects for A/B shots. |");
        sb.AppendLine("| `BALLISTIC_DEBUGVIEW=wireframe\\|normals\\|depth` | Renderer debug views. |");
        sb.AppendLine();
        sb.AppendLine("Live editor control: named pipe `\\\\.\\pipe\\BallisticEditor` (newline JSON `{id,method,params}`) " +
                      "or the MCP server `BallisticEngine.Mcp/bin/Debug/net9.0/BallisticEngine.Mcp.exe` (stdio, 16 tools). " +
                      "Remote edits are undoable and behave exactly like human edits.");
        sb.AppendLine();
        sb.AppendLine($"Structured logs: `Library/Logs/engine.jsonl` (one JSON object per line, truncated per session).");
        sb.AppendLine();

        // ---- project map ----------------------------------------------------------
        sb.AppendLine("## This project");
        sb.AppendLine();
        string? startup = project.Manifest?.StartupScene?.Replace('\\', '/');
        var scenes = new List<string>();
        int assetTotal = 0;
        var byImporter = new SortedDictionary<string, int>(StringComparer.Ordinal);
        foreach ((string path, MetaFile meta) in AssetsCommand.EnumerateMetas(root)) {
            assetTotal++;
            string importer = string.IsNullOrEmpty(meta.Importer) ? "(none)" : meta.Importer;
            byImporter[importer] = byImporter.GetValueOrDefault(importer) + 1;
            if (path.EndsWith(".scene", StringComparison.OrdinalIgnoreCase))
                scenes.Add(path);
        }

        sb.AppendLine("### Scenes");
        if (scenes.Count == 0)
            sb.AppendLine("(none yet — create one with the editor or `bal scene add-entity`)");
        foreach (string scene in scenes)
            sb.AppendLine($"- `{scene}`" + (string.Equals(scene, startup, StringComparison.OrdinalIgnoreCase) ? " **(startup)**" : ""));
        sb.AppendLine();

        var engineAssembly = typeof(SceneManager).Assembly;
        var scriptComponents = ComponentRegistry.Menu.Concat(ComponentRegistry.SceneMenu)
            .Where(e => e.Type.Assembly != engineAssembly)
            .Select(e => e.Type.Name).Distinct().OrderBy(n => n, StringComparer.Ordinal).ToList();
        sb.AppendLine("### Game-script components");
        sb.AppendLine(scriptComponents.Count == 0
            ? "(none — game code is any .cs under Assets/, hot-reloaded; `bal schema` lists engine components)"
            : string.Join(", ", scriptComponents.Select(n => $"`{n}`")) +
              " — details via `bal schema --type <Name>`. Source: .cs files under `Assets/`.");
        sb.AppendLine();

        sb.AppendLine($"### Assets ({assetTotal} total)");
        foreach ((string importer, int count) in byImporter)
            sb.AppendLine($"- {importer}: {count}");
        sb.AppendLine();

        sb.AppendLine("## Working rules");
        sb.AppendLine("- Reference assets by PATH (`Assets/...`), never invent guids; ids are minted by the tools.");
        sb.AppendLine("- After scene edits: `bal validate`. After gameplay changes: `bal simulate` with watches. After visual changes: `bal render` + `bal imgdiff` against a baseline.");
        sb.AppendLine("- Game scripts: lifecycle overrides (`Tick`, `OnBegin`, ...) must be `protected` (not `protected internal`). Compile errors block play, not the editor.");
        sb.AppendLine("- Prefer numeric verification (`simulate --watch`) over screenshot-staring; use the ID map to ask \"what is on screen where\".");

        File.WriteAllText(outPath, sb.ToString());
        Json.Write(new { ok = true, path = outPath, scenes = scenes.Count, scriptComponents = scriptComponents.Count, assets = assetTotal });
        return 0;
    }
}
